language: go

go:
  - 1.4

env:
    matrix:
        - PLAYBOOK="algorithms/sorting/bubble-sort"
        - PLAYBOOK="algorithms/algebraic/pascals-triangle"
        - PLAYBOOK="encoding/json/basetypes-marshalling"
        - PLAYBOOK="encoding/json/custom-marshaller"
        - PLAYBOOK="net/http/graceful-service-termination"
        - PLAYBOOK="net/http/https-aws-ebs-nginx"
        - PLAYBOOK="net/http/programmatic-http-redirect"
        - PLAYBOOK="net/http/request-caching"

script: "make build $PLAYBOOK"